namespace Fuyu.Server.BSG.DTO.Profiles.Bonusses
{
	public enum EBonusType
	{
		EnergyRegeneration,
		HydrationRegeneration,
		HealthRegeneration,
		MaximumEnergyReserve,
		ExperienceRate,
		QuestMoneyReward,
		ScavCooldownTimer,
		StashSize,
		UnlockItemCraft,
		UnlockItemPassiveCreation,
		UnlockRandomItemCreation,
		SkillGroupLevelingBoost,
		SkillLevelingBoost,
		DebuffEndDelay,
		RagfairCommission,
		InsuranceReturnTime,
		UnlockWeaponModification,
		UnlockScavPlay,
		UnlockAddOffer,
		UnlockItemCharge,
		ReceiveItemBonus,
		UnlockUniqueId,
		IncreaseCanisterSlots,
		AdditionalSlots,
		FuelConsumption,
		TextBonus,
		RepairWeaponBonus,
		RepairArmorBonus,
		UnlockWeaponRepair,
		UnlockArmorRepair,
		StashRows
	}
}